name: mapview
description: A container enabled scaling and dragging its inner child widget.
version: 0.1.0
homepage:
environment: {sdk: ">=3.4.3 <4.0.0", flutter: ">=3.22.0"}

dependencies:
  flutter: {sdk: flutter}

dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^3.0.0

flutter:
